name: Ruby Gem

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  spec:
    name: Spec
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ${{ matrix.setup }}
    - run: |
        git submodule update --init
        rake spec
    strategy:
      matrix:
        ruby: [3.1.0-preview1, 3.0.3, 3.0.2, 2.7.5, 2.7.4, 2.6.9, 2.6.8]
        runner:
          - macos-11
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
        exclude:
          - ruby: 3.1.0-preview1
            runner: windows-2019
          - ruby: 3.0.3
            runner: windows-2019
          - ruby: 2.7.5
            runner: windows-2019
          - ruby: 2.6.9
            runner: windows-2019
        include:
          - runner: macos-11
            setup: |
              brew update
              brew install protobuf
          - runner: ubuntu-18.04
            setup: sudo apt-get install libprotobuf-dev protobuf-compiler
          - runner: ubuntu-20.04
            setup: sudo apt-get install libprotobuf-dev protobuf-compiler
          - runner: windows-2019
            setup: pacman -S --noconfirm mingw-w64-x86_64-protobuf
